name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Delete node_modules and package-lock.json
      run: rm -rf node_modules package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
